name: Chromadb restpoint API
description: A rest API server to upsert documents into chromadb
author: Davide Vergari (dvergari_at_cloudera_dot_com)
specification_version: 1.0
prototype_version: 1.0


environment_variables:
  COLLECTION_NAME:
    default: "cml-default"
    description: "Enter preferred collection name for Chroma DB to store document embeddings in."
    required: true
  
  DEBUG:
    default: 0
    description: "Enter '1' to enable application debug. May impact performance"
    required: false
  

runtimes:
  - editor: JupyterLab
    kernel: Python 3.10
    edition: Standard

tasks:
  - type: run_session
    name: Install dependencies
    script: 00_install-dependencies/install_requirements.py
    short_summary: Install Package Dependencies
    kernel: python3
    cpu: 2
    memory: 8
  - type: run_session
    name: Setup Chroma Vector DB
    script: 01_setup-chroma/setup-chroma.py
    short_summary: Setup Chroma Vector DB
    kernel: python3
    cpu: 1
    memory: 2
  - type: start_application
    name: CML Chroma Server REST API Server
    subdomain: cml-chroma-server
    script: 2_application/chroma-app.py
    short_summary: Launch Chroma Server
    long_summary: Launch Chroma Server REST API application. Remember to enable unauthenticated app access for external access to the UI.
    cpu: 2
    memory: 8
    environment_variables:
      TASK_TYPE: START_APPLICATION

